=== ShoosounS47/qdev-wrappers/qdev_wrappers/templates/qcodesrc_schema.json
{
    "type": "object",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "properties": {
        "gui": {
            "type": "object",
            "properties": {
                "pyqtmaxplots": {
                    "type": "integer",
                    "default": 100,
                    "description": "Maximum number of PyQtPlots to automatically keep in memory"
                },
                "notebook": {
                    "type": "boolean",
                    "default": true,
                    "description": "Use notebook frontend"
                },
                "plotlib": {
                    "type": [
                        "string",
                        "null"
                    ],
                    "default": "all",
                    "description": "Plotting library set to null to run without plotting",
                    "enum": [
                        "QT",
                        "matplotlib",
                        "all",
                        null
                    ]
                }
            },
            "description": "controls gui of qcodes",
            "required": [
                "notebook",
                "plotlib",
                "pyqtmaxplots"
            ]
        },
        "core": {
            "type": "object",
            "properties": {
                "default_fmt": {
                    "type": "string",
                    "default": "data/{date}/#{counter}_{name}_{time}",
                    "description": "default location formatter"
                },
                "loglevel": {
                    "type": "string",
                    "default": "DEBUG",
                    "description": "control logging  level",
                    "enum": [
                        "CRITICAL",
                        "ERROR",
                        "WARNING",
                        "INFO",
                        "DEBUG"
                    ]
                }
            },
            "description": "controls core settings of qcodes",
            "required": [
                "loglevel"
            ]
        },
        "user": {
            "type": "object",
            "properties": {
                "scriptfolder": {
                    "type": "string",
                    "default": "/",
                    "description": "Location of scripts for general experiments"
                },
                "mainfolder": {
                    "type": "string",
                    "default": "",
                    "description": "Location of experiments"
                }
            },
            "description": "controls user settings of qcodes"
        },
        "station_configurator": {
            "type": "object",
            "properties": {
                "enable_forced_reconnect": {
                    "type": "boolean",
                    "default": false,
                    "description": "if set to true, on instantiation of an existing instrument, the existing will be disconnected."
                },
                "default_folder": {
                    "type": ["string", "null"],
                    "default": null,
                    "description": "default folder where to look for a station configurator config file"
                },
                "default_file": {
                    "type": ["string", "null"],
                    "default": null,
                    "description": "default file name, specifying the file to load, when none is specified. Can be a relative or absolute path"
                }

            },
            "description": "Setting for the StationConfigurator module in qdev-wrappers"
        }
    },
    "description": "schema for a qcodes config file",
    "required": [
        "gui",
        "core",
        "user"
    ]
}

=== ShoosounS47/qdev-wrappers/examples/station_configurator/qcodesrc.json
{
    "gui": {
        "pyqtmaxplots": 20,
        "notebook": true,
        "plotlib": "all"
    },
    "core": {
        "default_fmt": "data/{date}/#{counter}_{name}_{time}",
        "loglevel": "WARNING"
    },
    "user": {
        "scriptfolder": "/Users/natalie/Documents/PhD/Qdev/QcodesRelated/QcodesExperiments/ExperimentScripts",
        "mainfolder": "/Users/natalie/Documents/PhD/Qdev/QcodesRelated/QcodesExperiments/Qcodes_test_data"
    },
    "station_configurator": {
        "enable_forced_reconnect": false,
        "default_folder": "C:\\Users\\a-dovoge\\repos\\qdev-wrappers\\examples\\station_configurator",
        "default_file": "testSetupConfig.yaml"
    }
}
